apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.appname }}
spec:
  selector:
    app: {{ .Values.service.appname }}
  ports:
    {{- range $port := .Values.service.ports }}
    - name: {{ $port.name }}
      protocol: {{ $port.protocol }}
      port: {{ $port.port }}
    {{- end }}
  clusterIP: None